Algoritmo "contagem regreciva"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 24/03/2025
Var
// Seção de Declarações das variáveis 

   n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("Escreva um número positivo: ")
   leia (n)

   enquanto n <> 0 faca
      n <- n - 1
      escreval (" ", n)
   fimenquanto

Fimalgoritmo