Algoritmo "crecente"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 24/03/2025
Var
// Seção de Declarações das variáveis 

   pn: real
   sn: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("escreva o primeiro número: ")
   leia (pn)
   escreva ("escreva o segundo número: ")
   leia (sn)
   
  enquanto pn <> sn faca
      se (pn < sn) entao
      escreval ("essa serie de números é crecente")
          senao
      escreval ("essa serie de números é decrecente")
      fimse
   escreva ("escreva o primeiro número: ")
   leia (pn)
   escreva ("escreva o segundo número: ")
   leia (sn)
   fimenquanto
   

   



Fimalgoritmo