Algoritmo "enquanto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 24/03/2025
Var
// Seção de Declarações das variáveis 

   n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   n <- 0

   enquanto (n <= 1000) faca
      escreval ("o número é ", n)
       n <- n + 1
   fimenquanto



Fimalgoritmo