Algoritmo "soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/03/2025
Var
// Seção de Declarações das variáveis 

   n, s : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   s <- 0

   escreval ("Digite o número (0 para sair)")
   leia (n)

   enquanto (n <> 0 faca)
     s <- s + n
     escreval ("Digite outro número (0 para sair)")
     leia (n)
   fimenquanto
   
   escreval ("A soma dos dos números é: ", s)
   

Fimalgoritmo