Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 24/03/2025
Var
// Seção de Declarações das variáveis 

   n: inteiro
   m: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("escreva a tabuada que vc quer: ")
   leia (n)

   enquanto m <> 10 faca
      m <- m + 1

      escreval (n," X ", m, " = ", n * m)
   fimenquanto

Fimalgoritmo