Algoritmo "atividade 5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 10/03/2025
Var
// Seção de Declarações das variáveis
 
   dia : real
   cartao : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("Que dia da semana é hoje: ")
   leia (dia)
   escreva ("Vc tem o cartão de fidalidade: ")
   leia (cartao)

// se

   se (dia="quarta") e (cartao="sim")entao
      escreval ("Promção disponivel!")
   senao
      escreval ("Promoção indisponivel!")
   fimse

Fimalgoritmo