Algoritmo "atividade 4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 10/03/2025
Var
// Seção de Declarações das variáveis 

   idade : inteiro
   sta : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("Quantos anos vc tem: ")
   leia (idade)
   escreva ("Vc ainda é estudante: ")
   leia (sta)
   
// se

   se (idade<= 18) ou (sta= "sim")entao
      escreval ("Vc está isento")
   senao
      escreval ("Vc não está insento")
   fimse

Fimalgoritmo