Algoritmo "atividade1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : An Julia
// Data atual  : 10/03/2025
Var
// Seção de Declarações das variáveis 

   nota : real
   fre : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("Digite a sua nota aqui: ")
   leia (nota)
   escreva ("Digite a sua frequencia aqui: ")
   leia (fre)

   se (nota>=8) e (fre>=75)entao
      escreval ("Elegível para a bolsa!")
   senao
      escreval ("Não elegível para a bolsa!")
   fimse

Fimalgoritmo