Algoritmo "atividade 2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 10/03/2025
Var
// Seção de Declarações das variáveis 

   dindim : real
   idade : inteiro
   
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("Coloque a sua idade aqui: ")
   leia (idade)
   escreva ("Coloque o valor doproduto aqui: ")
   leia (dindim)
   
// se

   se (idade> 60) e (dindim> 100)entao
      escreval ("Vc tem direito a um desconto!")
   senao
      escreval ("Vc não tem nenhum desconto!")
   fimse

Fimalgoritmo