Algoritmo "atividade 3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 10/03/2025
Var
// Seção de Declarações das variáveis 

   peso : real
   altura : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("Coloque o quanto vc pesa aqui: ")
   leia (peso)
   escreva ("Coloque a sua altura aqui: ")
   leia (altura)
   
// se

   se (peso<= 80) ou (altura>= 1.80) entao
      escreval ("Adimitido!")
   senao
      escreval ("Não adimitido!")
   fimse

Fimalgoritmo