Algoritmo "operador e"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   : as duas condições tem q ser verdadeiras
// Autor(a)    : An a Julia
// Data atual  : 10/03/2025
Var
// Seção de Declarações das variáveis 

   usuario : caractere
   senha : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("Digite o usuário: ")
   leia (usuario)
   escreva ("Digite a senha: ")
   leia (senha)

   se (usuario = "cleiton") e (senha = "12345") entao
      escreval ("Pode acessar")
   senao
      escreval ("Não pode acessar")
   fimse

Fimalgoritmo