Algoritmo "condicionais"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   : condicional simples
// Autor(a)    : Ana Julia
// Data atual  : 24/02/2025
Var
// Seção de Declarações das variáveis 

   nota : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  escreval("Digite a nota do aluno: ")
  leia(nota)

//teste condicional

  se (nota>= 6) entao
     escreval("Aluno está aprovado!")
  fimse

  se (nota = 5) entao
     escreval("Nota é igual a 5")
  fimse
  
//os sinais de comparação
// > - maior
// < - menor
// >= maior ou igual
// <= menor ou igual
// <> diferente


Fimalgoritmo