Algoritmo "maior que 100"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   : Ler um número e mostrar se é > 100
// Autor(a)    : Ana Julia
// Data atual  : 24/02/2025
Var
// Seção de Declarações das variáveis 

   numero : real





Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval("Escreva o número aqui: "numero)
   leia(numero

//Conta

   se (numero >= 100)entao
      escreval("Seu valor é maior que 100")

   fimse



Fimalgoritmo