Algoritmo "menor dos tres"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   : um programa que le tres numeros e ve qual e o menor
// Autor(a)    : Ana Julia
// Data atual  : 24/02/2025
Var
// Seção de Declarações das variáveis 

   numero1 : inteiro
   numero2 : inteiro
   numero3 : inteiro
  
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval("Escreva o primeiro número: ")
   leia(numero1)
   escreval("Escreva o segundo número: ")
   leia(numero2)
   escreval("Escreva o terceiro número: ")
   leia(numero3)










Fimalgoritmo