Algoritmo "positivo ou negativo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   : um algoritmo que leia um número negativo ou um número positivo
// Autor(a)    : Ana Julia
// Data atual  : 24/02/2025
Var
// Seção de Declarações das variáveis 

   numero : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval("Escreva o seu número: ")
   leia(numero)

   se (numero>= 0)entao
      escreval ("Número positivo")
   senao
      escreval ("Número negativo")
   fimse

Fimalgoritmo