Algoritmo "se senao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   : Exemplo de condicional composta
// Autor(a)    : Ana Julia
// Data atual  : 24/02/2025
Var
// Seção de Declarações das variáveis 

   idade : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  escreval ("Escreva a sua idade: ")
  leia (idade)

//testar se a pessoa é maior de idade

  se (idade>=18) entao
     escreval ("Maior de idade")
  senao
     escreval ("Menor de idade")
  fimse


Fimalgoritmo