Algoritmo "atividade 5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :  atividade 5
// Autor(a)    : Ana Julia
// Data atual  : 31/03/2025
Var
// Seção de Declarações das variáveis 

   nota : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("Digite a sua nota: ")
   leia (nota)

// Se

   se (nota < 5)entao
      escreval ("Reprovado! :(")
     senao
     se (nota >= 5) e (nota <= 6.9)entao
        escreval ("Recuperação! :|")
       senao
           escreval ("Aprovado! :)")

    fimse
  fimse

Fimalgoritmo