Algoritmo "atividade 6"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   : atividade 6
// Autor(a)    : Ana Julia
// Data atual  : 31/03/2025
Var
// Seção de Declarações das variáveis 

   card : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval ("Escreva o número do seu pedido: ")
   leia (card)

// Escolha

   escolha card

     caso 1: escreval ("Lasanha")
     caso 2: escreval ("Pizza")
     caso 3: escreval ("Hanburguer")
     outrocaso: escreval ("Não temos isso no cardapio")
     
   fimescolha

Fimalgoritmo