Algoritmo "atividade 7"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   : atividade 7
// Autor(a)    : Ana Julia
// Data atual  : 31/03/2025
Var
// Seção de Declarações das variáveis 

   num : inteiro
   soma : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval ("Escreva um número: ")
   leia (num)

// enquanto

   enquanto num <> 0 faca
       soma <- soma + num
   escreval ("Escreva outro número: ")
   leia (num)

   fimenquanto

   escreval ("Soma: ",soma)

Fimalgoritmo