Algoritmo "circulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 17/02/2025
Var
// Seção de Declarações das variáveis 
   
   area : real

   raio : real

   total : real
   
   resultado : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval ("Digite o valor do raio do circulo")
   leia (raio)
   escreval ("Raio: ",raio)

//conta do raio

  total<- raio * 2
  resultado<- total * pi

  escreval ("AREA=",resultado)
Fimalgoritmo