Algoritmo "Idades"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 17/02/2025
Var
// Seção de Declarações das variáveis 

  nome1 : caracter
  nome2 : caracter
  
  
  idade1 : inteiro
  idade2 : inteiro
  media : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

  escreval ("Dados da primeira pessoa")
  escreval ("Escreva o seu nome:")
  leia (nome1)
  escreval ("Escreva a sua idade:")
  leia (idade1)
  escreval ("Nome: ", nome1)
  escreval ("Idade: ",idade1)
  
  escreval ("Dados da segunda pessoa")
  escreval ("Escreva o seu nome:")
  leia (nome2)
  escreval ("Escreva a sua idade:")
  leia (idade2)
  escreval ("Nome: ", nome2)
  escreval ("Idade: ",idade2)
  
//média das idades

  media<- (idade1 + idade2) /2

  escreval ("A idade média de ",nome1,nome2,"A média das idades é ", media)








Fimalgoritmo