Algoritmo "compras"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :  compras
// Autor(a)    : Ana Julia
// Data atual  : 10/02/2025
Var
// Seção de Declarações das variáveis 
 produto : real
 produto25 :real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval ("Valor do produto: ")
 leia (produto)
 
 //calculando almento 25%
  produto25<- produto + (produto/4)
  escreval ("Adicionado 25% de almento no produto", produto25)

Fimalgoritmo