Algoritmo "dados do aluno"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   : Mostra dados do aluno
// Autor(a)    : Ana Julia
// Data atual  : 10/02/2025
Var
// Seção de Declarações das variáveis 
 nomeAluno:caractere
 idadeAluno:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval ("Digite o seu nome: ")
 leia (nomeAluno)
 
 // vou mostrar o nome do aluno 5 vezes
 escreval ("O seu nome é ")
 escreval (nomeAluno)
 escreval (nomeAluno)
 escreval (nomeAluno)
 escreval (nomeAluno)
 escreval (nomeAluno)
Fimalgoritmo