Algoritmo "idade em meses"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :  Ari
// Descrição   :  mostrar idade em meses
// Autor(a)    :  Ana Julia
// Data atual  : 10/02/2025
Var
// Seção de Declarações das variáveis 
 idade_anos : inteiro
 idade_meses : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval ("Digite a sua idade: ")
 leia (idade_anos)
 
 //calculando idade em meses
 idade_meses <- idade_anos * 12

 //mostrando idade em meses
 escreval ("Sua idade em meses: ", idade_meses)
 
Fimalgoritmo