Algoritmo "Media"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   : Media dos 3 bimestres do ano
// Autor(a)    : Ana Julia
// Data atual  : 10/02/2025
Var
// Seção de Declarações das variáveis 
 bimestreUm : real
 bimestreDois : real
 bimestreTres : real
 media : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval ("Media do primeiro bimestre: ")
 leia (bimestreUm)
 escreval ("Media do segundo bimestre: ")
 leia (bimestreDois)
 escreval ("media do terceiro bimestre: ")
 leia (bimestreTres)
 
 media<- (bimestreUm + bimestreDois + bimestreTres)/3
 escreval ("Media do Ano ", media)



Fimalgoritmo