Algoritmo "1,2 e 3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 17/03/2025
Var
// Seção de Declarações das variáveis 

   n : inteiro
   
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("escreva um número de 1 a 3 : ")
   leia (n)


   escolha n
      caso 1
        escreval ("Alimentos")
      caso 2
        escreval ("Elêtronicos")
      caso 3
        escreval ("Vestuário")
      outrocaso
        escreval ("fora do sistema")
   fimescolha

Fimalgoritmo