Algoritmo "1,2,3 e 4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   : 1,2,3 e 4!!!
// Autor(a)    : Ana Julia
// Data atual  : 17/03/2025
Var
   // Seção de Declarações das variáveis
   n : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreva ("Digite um número de 1 a 4: ")
   leia (n)

   // se

   se (n=1)entao
      escreval ("O número que vc escreval é o UM!3")
   senao
      se (n=2)entao
         escreval ("O número que vc escrevel é o DOIS!")
      senao
         se (n=3)entao
            escreval ("O número que vc escrevel é o TRÊS!")
         senao
            se (n=4)entao
               escreval ("O número que vc escrevel é o QUATRO!")
            senao
               escreval ("Número invalid
            fimse
         fimse
      fimse
   fimse

Fimalgoritmo