Algoritmo "mes"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 17/03/2025
Var
// Seção de Declarações das variáveis 

   mes : inteiro
   
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval ("Escreva o mes q vc está: ")
   leia (mes)


   escolha mes
       caso (1)
         escreval ("janeiro")
       caso (2)
         escreval ("fevereiro")
       caso (3)
         escreval ("março")
       caso (4)
         escreval ("abril")
       caso (5)
         escreval ("maio")
        caso (6)
         escreval ("junho")
       caso (7)
         escreval ("julho")
       caso (8)
         escreval ("agosto")
       caso (9)
         escreval ("setenbro")
       caso (10)
         escreval ("outubro")
       caso (11)
         escreval ("novembro")
       caso (12)
         escreval ("dezembro")
       outrocaso
         escreval ("codigo invalido")
    fimescolha

Fimalgoritmo