Algoritmo "semana"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 17/03/2025
Var
// Seção de Declarações das variáveis 

   dia : inteiro
   
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

   escreva ("Escreva o dia de hj: ")
   leia (dia)

// escolha
 
   escolha dia
       caso (1)
         escreval ("domingo")
       caso (2)
         escreval ("segunda-feira")
       caso (3)
         escreval ("terça-feira")
       caso (4)
         escreval ("quarta-feira")
       caso (5)
         escreval ("quinta-feira")
        caso (6)
         escreval ("sexta-feira")
       caso (7)
         escreval ("sabado")
       outrocaso
         escreval ("codigo invalido")
    fimescolha

Fimalgoritmo