Algoritmo "boa noite"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 07/04/2025
Var
// Seção de Declarações das variáveis 

   cont : inteiro
   
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
// Quero dar boa noite 5 vezes

   para cont de 1 ate 1000 passo 1 faca
        escreval ("Boa Noite! ",cont)
   fimpara

   para cont de 1000 ate 0 passo -1 faca
        escreval ("Primeiro DS é top!",cont)
   fimpara
   
Fimalgoritmo