Algoritmo "contador"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 07/04/2025
Var
// Seção de Declarações das variáveis 

   num,cont : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreva ("digite um número: ")
   leia (num)
   para cont de 1 ate num passo 1 faca
        escreval(cont)

   fimpara

Fimalgoritmo