Algoritmo "impar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 07/04/2025
Var
// Seção de Declarações das variáveis 

   num, cont : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval ("Digite o valor de X: ")
   leia (num)

   para cont de 1 ate num passo 2 faca
      escreval ("",cont)


   fimpara

Fimalgoritmo