Algoritmo "decrecente"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 07/04/2025
Var
// Seção de Declarações das variáveis 

   num : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   escreval ("digite um número: ")
   leia (num)
   para num de num ate (num -3) passo -1 faca
        escreval("",num)

   fimpara

Fimalgoritmo