Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Ari
// Descrição   :
// Autor(a)    : Ana Julia
// Data atual  : 07/04/2025
Var
// Seção de Declarações das variáveis 

   num, soma, cont : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval ("Digite o número da tabuada: ")
        leia (num)
        
    para cont de 1 ate 10 passo 1 faca
        soma <- cont * num
        escreval (num, " X" , cont," =" ,soma)
     fimpara
   
Fimalgoritmo